const countries = [
    {
        alpha3Code: 'AFG',
        name: "afghanistan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -137,
        score: "f"
    },
    {
        alpha3Code: 'ALB',
        name: "albania",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.4,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 96,
        score: "d+"
    },
    {
        alpha3Code: 'DZA',
        name: "algeria",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -75,
        score: "f"
    },
    {
        alpha3Code: 'AND',
        name: "andorra",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 255,
        score: "b"
    },
    {
        alpha3Code: 'AGO',
        name: "angola",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 183,
        score: "c+"
    },
    {
        alpha3Code: 'ATG',
        name: "antigua & barbuda",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 3,
        score: "d-"
    },
    {
        alpha3Code: 'ARG',
        name: "argentina",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 2.5,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 260,
        score: "b"
    },
    {
        alpha3Code: 'ARM',
        name: "armenia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 64,
        score: "d"
    },
    {
        alpha3Code: 'ABW',
        name: "aruba",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 138,
        score: "c-"
    },
    {
        alpha3Code: 'AUS',
        name: "australia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 304,
        score: "a-"
    },
    {
        alpha3Code: 'AUT',
        name: "austria",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 305,
        score: "a-"
    },
    {
        alpha3Code: 'AZE',
        name: "azerbaijan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 1,
        score: "d-"
    },
    {
        alpha3Code: 'BHR',
        name: "bahrain",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -15,
        score: "f"
    },
    {
        alpha3Code: 'BGD',
        name: "bangladesh",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -15,
        score: "f"
    },
    {
        alpha3Code: 'BRB',
        name: "barbados",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: -10,
        score: "f"
    },
    {
        alpha3Code: 'BLR',
        name: "belarus",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 13,
        score: "d-"
    },
    {
        alpha3Code: 'BEL',
        name: "belgium",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 343,
        score: "a-"
    },
    {
        alpha3Code: 'BLZ',
        name: "belize",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 5.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: -9,
        score: "f"
    },
    {
        alpha3Code: 'BEN',
        name: "benin",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 10,
        score: "d-"
    },
    {
        alpha3Code: 'BTN',
        name: "bhutan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 16,
        score: "d-"
    },
    {
        alpha3Code: 'BOL',
        name: "bolivia",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 223,
        score: "b-"
    },
    {
        alpha3Code: 'BIH',
        name: "bosnia & herzegovina",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 138,
        score: "c-"
    },
    {
        alpha3Code: 'BWA',
        name: "botswana",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 108,
        score: "d+"
    },
    {
        alpha3Code: 'BRA',
        name: "brazil",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 8.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 248,
        score: "b"
    },
    {
        alpha3Code: 'BRN',
        name: "brunei",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -200,
        score: "f"
    },
    {
        alpha3Code: 'BGR',
        name: "bulgaria",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 159,
        score: "c"
    },
    {
        alpha3Code: 'BFA',
        name: "burkinafaso",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 53,
        score: "d-"
    },
    {
        alpha3Code: 'BDI',
        name: "burundi",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -22,
        score: "f"
    },
    {
        alpha3Code: 'CPV',
        name: "cabo verde",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 125,
        score: "c-"
    },
    {
        alpha3Code: 'KHM',
        name: "cambodia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 4,
        score: "d-"
    },
    {
        alpha3Code: 'CMR',
        name: "cameroon",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -64,
        score: "f"
    },
    {
        alpha3Code: 'CAN',
        name: "canada",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 383,
        score: "a"
    },
    {
        alpha3Code: 'CYM',
        name: "cayman islands",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 60,
        score: "d"
    },
    {
        alpha3Code: 'CAF',
        name: "central african republic",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -19,
        score: "f"
    },
    {
        alpha3Code: 'TCD',
        name: "chad",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -38,
        score: "f"
    },
    {
        alpha3Code: 'CHL',
        name: "chile",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 1.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 307,
        score: "a-"
    },
    {
        alpha3Code: 'CHN',
        name: "china",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: 31,
        score: "d-"
    },
    {
        alpha3Code: 'COL',
        name: "colombia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 4.6,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 239,
        score: "b"
    },
    {
        alpha3Code: 'COM',
        name: "comoros",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -56,
        score: "f"
    },
    {
        alpha3Code: 'COG',
        name: "congo republic",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 16,
        score: "d-"
    },
    {
        alpha3Code: 'CRI',
        name: "costa rica",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 1.8,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 259,
        score: "b"
    },
    {
        alpha3Code: 'CIV',
        name: "cote d'ivoire",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: -25,
        score: "f"
    },
    {
        alpha3Code: 'HRV',
        name: "croatia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 288,
        score: "b+"
    },
    {
        alpha3Code: 'CUB',
        name: "cuba",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 279,
        score: "b+"
    },
    {
        alpha3Code: 'CUW',
        name: "curaçao",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 85,
        score: "d"
    },
    {
        alpha3Code: 'CYP',
        name: "cyprus",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 192,
        score: "c+"
    },
    {
        alpha3Code: 'CZE',
        name: "czech republic",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 185,
        score: "c+"
    },
    {
        alpha3Code: 'COD',
        name: "democratic republic of congo",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: -27,
        score: "f"
    },
    {
        alpha3Code: 'DNK',
        name: "denmark",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 347,
        score: "a-"
    },
    {
        alpha3Code: 'DJI',
        name: "djibouti",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 5,
        score: "d-"
    },
    {
        alpha3Code: 'DMA',
        name: "dominica",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -47,
        score: "f"
    },
    {
        alpha3Code: 'DOM',
        name: "dominican republic",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 4.4,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 3,
        score: "d-"
    },
    {
        alpha3Code: 'ECU',
        name: "ecuador",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 3.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 223,
        score: "b-"
    },
    {
        alpha3Code: 'EGY',
        name: "egypt",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -95,
        score: "f"
    },
    {
        alpha3Code: 'SLV',
        name: "el salvador",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'No information',
        transMurderRates: 9.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 58,
        score: "d-"
    },
    {
        alpha3Code: 'GNQ',
        name: "equatorial guinea",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: 40,
        score: "d-"
    },
    {
        alpha3Code: 'ERI',
        name: "eritrea",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -75,
        score: "f"
    },
    {
        alpha3Code: 'EST',
        name: "estonia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.8,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 223,
        score: "b-"
    },
    {
        alpha3Code: 'SWZ',
        name: "eswatini",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -26,
        score: "f"
    },
    {
        alpha3Code: 'ETH',
        name: "ethiopia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -83,
        score: "f"
    },
    {
        alpha3Code: 'FJI',
        name: "fiji",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 2.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 123,
        score: "c-"
    },
    {
        alpha3Code: 'FIN',
        name: "finland",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 300,
        score: "a-"
    },
    {
        alpha3Code: 'FRA',
        name: "france",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 338,
        score: "a-"
    },
    {
        alpha3Code: 'GAB',
        name: "gabon",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 10,
        score: "d-"
    },
    {
        alpha3Code: 'GMB',
        name: "gambia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -139,
        score: "f"
    },
    {
        alpha3Code: 'GEO',
        name: "georgia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.8,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 154,
        score: "c"
    },
    {
        alpha3Code: 'DEU',
        name: "germany",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 309,
        score: "a-"
    },
    {
        alpha3Code: 'GHA',
        name: "ghana",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -59,
        score: "f"
    },
    {
        alpha3Code: 'GRC',
        name: "greece",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 239,
        score: "b"
    },
    {
        alpha3Code: 'GRD',
        name: "grenada",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 43,
        score: "d-"
    },
    {
        alpha3Code: 'GUM',
        name: "guam",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 299,
        score: "a-"
    },
    {
        alpha3Code: 'GTM',
        name: "guatemala",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 3.9,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 3,
        score: "d-"
    },
    {
        alpha3Code: 'GIN',
        name: "guinea",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -60,
        score: "f"
    },
    {
        alpha3Code: 'GNB',
        name: "guinea-bissau",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 0,
        score: "d-"
    },
    {
        alpha3Code: 'GUY',
        name: "guyana",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 5.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -162,
        score: "f"
    },
    {
        alpha3Code: 'HTI',
        name: "haiti",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 78,
        score: "d"
    },
    {
        alpha3Code: 'HND',
        name: "honduras",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 11.8,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 65,
        score: "d"
    },
    {
        alpha3Code: 'HKG',
        name: "hong kong ",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 74,
        score: "d"
    },
    {
        alpha3Code: 'HUN',
        name: "hungary",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: 136,
        score: "c-"
    },
    {
        alpha3Code: 'ISL',
        name: "iceland",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 330,
        score: "a-"
    },
    {
        alpha3Code: 'IND',
        name: "india",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 177,
        score: "c"
    },
    {
        alpha3Code: 'IDN',
        name: "indonesia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -7,
        score: "f"
    },
    {
        alpha3Code: 'IRN',
        name: "iran",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -105,
        score: "f"
    },
    {
        alpha3Code: 'IRQ',
        name: "iraq",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -28,
        score: "f"
    },
    {
        alpha3Code: 'IRL',
        name: "ireland",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 320,
        score: "a-"
    },
    {
        alpha3Code: 'ISR',
        name: "israel",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 215,
        score: "b-"
    },
    {
        alpha3Code: 'ITA',
        name: "italy",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.8,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 169,
        score: "c"
    },
    {
        alpha3Code: 'JAM',
        name: "jamaica",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.7,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -61,
        score: "f"
    },
    {
        alpha3Code: 'JPN',
        name: "japan",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 96,
        score: "d+"
    },
    {
        alpha3Code: 'JOR',
        name: "jordan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -15,
        score: "f"
    },
    {
        alpha3Code: 'KAZ',
        name: "kazakhstan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: 2,
        score: "d-"
    },
    {
        alpha3Code: 'KEN',
        name: "kenya",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -62,
        score: "f"
    },
    {
        alpha3Code: 'KIR',
        name: "kiribati",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -70,
        score: "f"
    },
    {
        alpha3Code: 'BRB',
        name: "kosovo",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 196,
        score: "c+"
    },
    {
        alpha3Code: 'KWT',
        name: "kuwait",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -180,
        score: "f"
    },
    {
        alpha3Code: 'KGZ',
        name: "kyrgyzstan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 32,
        score: "d-"
    },
    {
        alpha3Code: 'LAO',
        name: "laos",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 71,
        score: "d"
    },
    {
        alpha3Code: 'LVA',
        name: "latvia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 95,
        score: "d+"
    },
    {
        alpha3Code: 'LBN',
        name: "lebanon",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -58,
        score: "f"
    },
    {
        alpha3Code: 'LSO',
        name: "lesotho",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 80,
        score: "d"
    },
    {
        alpha3Code: 'LBR',
        name: "liberia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -49,
        score: "f"
    },
    {
        alpha3Code: 'LBY',
        name: "libya",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -150,
        score: "f"
    },
    {
        alpha3Code: 'LIE',
        name: "liechtenstein",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 142,
        score: "c-"
    },
    {
        alpha3Code: 'LTU',
        name: "lithuania",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: 150,
        score: "c"
    },
    {
        alpha3Code: 'LUX',
        name: "luxembourg",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 320,
        score: "a-"
    },
    {
        alpha3Code: 'MAC',
        name: "macau",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 65,
        score: "d"
    },
    {
        alpha3Code: 'MDG',
        name: "madagascar",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 26,
        score: "d-"
    },
    {
        alpha3Code: 'MWI',
        name: "malawi",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -163,
        score: "f"
    },
    {
        alpha3Code: 'MYS',
        name: "malaysia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.5,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -160,
        score: "f"
    },
    {
        alpha3Code: 'MDV',
        name: "maldives",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -80,
        score: "f"
    },
    {
        alpha3Code: 'MLI',
        name: "mali",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 12,
        score: "d-"
    },
    {
        alpha3Code: 'MLT',
        name: "malta",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 370,
        score: "a"
    },
    {
        alpha3Code: 'MHL',
        name: "marshall islands",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 85,
        score: "d"
    },
    {
        alpha3Code: 'MRT',
        name: "mauritania",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -141,
        score: "f"
    },
    {
        alpha3Code: 'MUS',
        name: "mauritius",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0.8,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: 15,
        score: "d-"
    },
    {
        alpha3Code: 'MEX',
        name: "mexico",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 5.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 212,
        score: "b-"
    },
    {
        alpha3Code: 'FSM',
        name: "micronesia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 50,
        score: "d-"
    },
    {
        alpha3Code: 'MDA',
        name: "moldova",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 95,
        score: "d+"
    },
    {
        alpha3Code: 'MCO',
        name: "monaco",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 62,
        score: "d"
    },
    {
        alpha3Code: 'MNG',
        name: "mongolia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 117,
        score: "d+"
    },
    {
        alpha3Code: 'MNE',
        name: "montenegro",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 167,
        score: "c"
    },
    {
        alpha3Code: 'MAR',
        name: "morocco",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -89,
        score: "f"
    },
    {
        alpha3Code: 'MOZ',
        name: "mozambique",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 62,
        score: "d"
    },
    {
        alpha3Code: 'MMR',
        name: "myanmar",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -73,
        score: "f"
    },
    {
        alpha3Code: 'NAM',
        name: "namibia",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: 58,
        score: "d-"
    },
    {
        alpha3Code: 'NRU',
        name: "nauru",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 0,
        score: "d-"
    },
    {
        alpha3Code: 'NPL',
        name: "nepal",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 206,
        score: "c+"
    },
    {
        alpha3Code: 'NLD',
        name: "netherlands",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 373,
        score: "a"
    },
    {
        alpha3Code: 'NZL',
        name: "new zealand",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.4,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 299,
        score: "a-"
    },
    {
        alpha3Code: 'NIC',
        name: "nicaragua",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'No information',
        transMurderRates: 1.4,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 156,
        score: "c"
    },
    {
        alpha3Code: 'NER',
        name: "niger",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 14,
        score: "d-"
    },
    {
        alpha3Code: 'NGA',
        name: "nigeria",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -190,
        score: "f"
    },
    {
        alpha3Code: 'MKD',
        name: "north macedonia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 163,
        score: "c"
    },
    {
        alpha3Code: 'MNP',
        name: "northern mariana islands",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 85,
        score: "d"
    },
    {
        alpha3Code: 'NOR',
        name: "norway",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 358,
        score: "a"
    },
    {
        alpha3Code: 'OMN',
        name: "oman",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -145,
        score: "f"
    },
    {
        alpha3Code: 'PAK',
        name: "pakistan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.5,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -47,
        score: "f"
    },
    {
        alpha3Code: 'PLW',
        name: "palau",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 0,
        score: "d-"
    },
    {
        alpha3Code: 'PAN',
        name: "panama",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 1.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 51,
        score: "d-"
    },
    {
        alpha3Code: 'PNG',
        name: "papua new guinea",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -81,
        score: "f"
    },
    {
        alpha3Code: 'PRY',
        name: "paraguay",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 1.7,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 30,
        score: "d-"
    },
    {
        alpha3Code: 'PER',
        name: "peru",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 1.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 206,
        score: "c+"
    },
    {
        alpha3Code: 'PHL',
        name: "philippines",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.7,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 62,
        score: "d"
    },
    {
        alpha3Code: 'POL',
        name: "poland",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 82,
        score: "d"
    },
    {
        alpha3Code: 'PRT',
        name: "portugal",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 358,
        score: "a"
    },
    {
        alpha3Code: 'PRI',
        name: "puerto rico",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 5.6,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 245,
        score: "b"
    },
    {
        alpha3Code: 'QAT',
        name: "qatar",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -137,
        score: "f"
    },
    {
        alpha3Code: 'ROU',
        name: "romania",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 137,
        score: "c-"
    },
    {
        alpha3Code: 'RUS',
        name: "russia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -37,
        score: "f"
    },
    {
        alpha3Code: 'RWA',
        name: "rwanda",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: -29,
        score: "f"
    },
    {
        alpha3Code: 'ASM',
        name: "samoa",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: 48,
        score: "d-"
    },
    {
        alpha3Code: 'SMR',
        name: "san marino",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 238,
        score: "b"
    },
    {
        alpha3Code: 'STP',
        name: "sao tome & principe",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 0,
        score: "d-"
    },
    {
        alpha3Code: 'SAU',
        name: "saudi arabia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -196,
        score: "f"
    },
    {
        alpha3Code: 'SEN',
        name: "senegal",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -67,
        score: "f"
    },
    {
        alpha3Code: 'SRB',
        name: "serbia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 172,
        score: "c"
    },
    {
        alpha3Code: 'SYC',
        name: "seychelles",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 75,
        score: "d"
    },
    {
        alpha3Code: 'SLE',
        name: "sierra leone",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -73,
        score: "f"
    },
    {
        alpha3Code: 'SGP',
        name: "singapore",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 78,
        score: "d"
    },
    {
        alpha3Code: 'SXM',
        name: "sint maarten (dutch)",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 85,
        score: "d"
    },
    {
        alpha3Code: 'SVK',
        name: "slovakia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 191,
        score: "c+"
    },
    {
        alpha3Code: 'SVN',
        name: "slovenia",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 281,
        score: "b+"
    },
    {
        alpha3Code: 'SLB',
        name: "solomon island",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -85,
        score: "f"
    },
    {
        alpha3Code: 'SOM',
        name: "somalia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -140,
        score: "f"
    },
    {
        alpha3Code: 'ZAF',
        name: "south africa",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 317,
        score: "a-"
    },
    {
        alpha3Code: 'KOR',
        name: "south korea",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 92,
        score: "d+"
    },
    {
        alpha3Code: 'SSD',
        name: "south sudan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -116,
        score: "f"
    },
    {
        alpha3Code: 'ESP',
        name: "spain",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 356,
        score: "a"
    },
    {
        alpha3Code: 'LKA',
        name: "sri lanka",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -46,
        score: "f"
    },
    {
        alpha3Code: 'KNA',
        name: "st. kitts & nevis",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 43,
        score: "d-"
    },
    {
        alpha3Code: 'LCA',
        name: "st. lucia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -90,
        score: "f"
    },
    {
        alpha3Code: 'VCT',
        name: "st. vicent and the grenadines",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -70,
        score: "f"
    },
    {
        alpha3Code: 'SDN',
        name: "sudan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -159,
        score: "f"
    },
    {
        alpha3Code: 'SUR',
        name: "suriname",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 136,
        score: "c-"
    },
    {
        alpha3Code: 'SWE',
        name: "sweden",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 377,
        score: "a"
    },
    {
        alpha3Code: 'CHE',
        name: "switzerland",
        discriminationProtection: 'Constitutional protections',
        violenceCriminalization: 'Incitement',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 328,
        score: "a-"
    },
    {
        alpha3Code: 'TJK',
        name: "tajikistan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 24,
        score: "d-"
    },
    {
        alpha3Code: 'TWN',
        name: "taiwan",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 188,
        score: "c+"
    },
    {
        alpha3Code: 'TZA',
        name: "tanzania",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'Limited protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -120,
        score: "f"
    },
    {
        alpha3Code: 'THA',
        name: "thailand",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.3,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 141,
        score: "c-"
    },
    {
        alpha3Code: 'BHS',
        name: "bahamas",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 50,
        score: "d-"
    },
    {
        alpha3Code: 'TLS',
        name: "timor-leste",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 20,
        score: "d-"
    },
    {
        alpha3Code: 'TGO',
        name: "togo",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -55,
        score: "f"
    },
    {
        alpha3Code: 'TON',
        name: "tonga",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -130,
        score: "f"
    },
    {
        alpha3Code: 'TTO',
        name: "trinidad & tobago",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0.7,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 21,
        score: "d-"
    },
    {
        alpha3Code: 'TUN',
        name: "tunisia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -91,
        score: "f"
    },
    {
        alpha3Code: 'TCA',
        name: "turk & caicos",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 50,
        score: "d-"
    },
    {
        alpha3Code: 'TUR',
        name: "turkey",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0.7,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 40,
        score: "d-"
    },
    {
        alpha3Code: 'TKM',
        name: "turkmenistan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -60,
        score: "f"
    },
    {
        alpha3Code: 'TUV',
        name: "tuvalu",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -75,
        score: "f"
    },
    {
        alpha3Code: 'ARE',
        name: "united arab emirates",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Illegal',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -160,
        score: "f"
    },
    {
        alpha3Code: 'UGA',
        name: "uganda",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'No information',
        transMurderRates: 0.1,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -83,
        score: "f"
    },
    {
        alpha3Code: 'UKR',
        name: "ukraine",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 165,
        score: "c"
    },
    {
        alpha3Code: 'GBR',
        name: "united kingdom",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0.2,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 342,
        score: "a-"
    },
    {
        alpha3Code: 'USA',
        name: "united states",
        discriminationProtection: 'Limited protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 1.1,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: 292,
        score: "b+"
    },
    {
        alpha3Code: 'URY',
        name: "uruguay",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 4,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 305,
        score: "a-"
    },
    {
        alpha3Code: 'UZB',
        name: "uzbekistan",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -65,
        score: "f"
    },
    {
        alpha3Code: 'VEN',
        name: "venezuela",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '51-75%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 4.6,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 28,
        score: "d-"
    },
    {
        alpha3Code: 'VNM',
        name: "vietnam",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '26-50%',
        transgenderLegal: 'Legal to change gender but it requires sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 65,
        score: "d"
    },
    {
        alpha3Code: 'VIR',
        name: "virgin islands (us)",
        discriminationProtection: 'Broad protections',
        violenceCriminalization: 'Hate crimes',
        goodPlaceToLive: '76-100%',
        transgenderLegal: 'Legal to change gender without sex reassignment surgery',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Allowed',
        propaganda: 'Allowed',
        safetyIndex: 289,
        score: "b+"
    },
    {
        alpha3Code: 'YEM',
        name: "yemen",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Laws prevent the discussion of Pro-LGTBTQ+ issues',
        safetyIndex: -145,
        score: "f"
    },
    {
        alpha3Code: 'ZMB',
        name: "zambia",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -79,
        score: "f"
    },
    {
        alpha3Code: 'ZWE',
        name: "zimbabwe",
        discriminationProtection: 'No protections',
        violenceCriminalization: 'No protections',
        goodPlaceToLive: '0-25%',
        transgenderLegal: 'No information',
        transMurderRates: 0,
        illegalSameSexRelationships: 'Punishments range from jail time to the death penalty',
        propaganda: 'Allowed',
        safetyIndex: -52,
        score: "f"
    }
]

module.exports = countries